name: CI # 워크플로의 이름 지정

# 워크플로가 시작될 조건 지정
# main 브랜치에 푸시를 할 때마다 워크플로를 시작하도록 작성
on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest  # 실행 환경 지정

    #실행 스텝 지정
    #각 항목은 별도의 작업(uses) 또는 명령어(run)으로 이루어짐
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build